name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      
      - name: Install dependencies
        run: |
          npm install

      - name: run the tests
        run: |
          npm run all

      - name: show output files
        run: |
          pwd
          ls -R

      - name: archive dist directory
        uses: actions/upload-artifact@v5
        with:
          name: my-artifact
          path: ./dist/
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4


      - name: Set Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Unarchive the .dist directory
        uses: actions/download-artifact@v6
        with:
          name: my-artifact
          path: ./dist/
      
      - name: show the files to verify it is placed
        run:
          ls -R
      
      - name: run the action to test it
        uses: ./
        with:
          milliseconds: 1000
